CREATE OR REPLACE FUNCTION customer_information(
  reservation_id IN  HRS_OURDATABASE.RESERVATION.RESERVATION_ID%TYPE
) RETURN HRS_OURDATABASE.CUSTOMER%ROWTYPE
AS
 customer_row_record HRS_OURDATABASE.CUSTOMER%ROWTYPE;
 CID HRS_OURDATABASE.CUSTOMER.CUSTOMER_ID%TYPE;
BEGIN
  SELECT CUSTOMER_ID
  INTO   CID
  FROM   HRS_OURDATABASE.RESERVATION
  WHERE  RESERVATION_ID=reservation_id

  SELECT *
  INTO   customer_row_record
  FROM   HRS_OURDATABASE.CUSTOMER
  WHERE  CUSTOMER_ID=CID


  RETURN customer_row_record;
END;
/
/*
DECLARE
    CI  HRS_OURDATABASE.CUSTOMER%ROWTYPE;
BEGIN
     CI := customer_information(19);
		 DBMS_OUTPUT.PUT_LINE();
END;
/
 */