CREATE OR REPLACE FUNCTION customer_information(
  reservation_id IN  HRS_OURDATABASE.RESERVATION.RESERVATION_ID%TYPE
) RETURN HRS_OURDATABASE.ROOM%ROWTYPE
AS
 room_row_record HRS_OURDATABASE.ROOM%ROWTYPE;
 RID HRS_OURDATABASE.ROOM.ROOM_ID%TYPE;
BEGIN
  SELECT ROOM_ID
  INTO   RID
  FROM   HRS_OURDATABASE.RESERVATION
  WHERE  RESERVATION_ID=reservation_id

  SELECT *
  INTO   room_row_record
  FROM   HRS_OURDATABASE.ROOM
  WHERE  ROOM_ID=RID


  RETURN room_row_record;
END;
/
/*
DECLARE
    RI  HRS_OURDATABASE.CUSTOMER%ROWTYPE;
BEGIN
     RI := customer_information(19);
		 DBMS_OUTPUT.PUT_LINE();
END;
/
 */